# Generated by Django 2.0.5 on 2018-05-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_43', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='file',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='music',
            name='genre',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
